# This is technically out-dated, but version 2 offers us `depends_on`
# which is *incredibly* useful, and version 3 is really mainly updated
# for use in docker swarm, which... not interested in.
version: '2'

services:
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=blahgr_dev
      - POSTGRES_USER=blahgr
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5555:5432'
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "blahgr_dev", "-U", "blahgr" ]
        timeout: 45s
        interval: 10s
        retries: 10

  server:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=password
    volumes:
      - .:/blahgr
    ports:
      - '8000:8000'

volumes:
  pgdata:
