# Generated by Django 4.0.3 on 2022-03-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('author_id', 'title'), name='blog_post_author_id_title_uniq'),
        ),
    ]
