# Generated by Django 4.0.3 on 2022-03-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_blog_post_author_id_title_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='The title of the blog post', max_length=100),
        ),
    ]
